"""Build the canonical Bio2RDF (26-subgraph) schema files from the raw output of
schema_gnrator_Bio2RDF.py.

WHY THIS SCRIPT EXISTS
-----------------------
The canonical schema files this script writes already exist in the repository
and are already used throughout the analysis and the manuscript (see "Outputs
and downstream usage" below). What was missing was the step in between: nothing
in the repository turned schema_gnrator_Bio2RDF.py's raw query output into those
canonical files, so there was no way to see, or to reproduce, how they were built.
This script reconstructs that missing step. It does not perform any new
analysis, apply any new filtering logic, or change any previously reported
number — it only makes explicit and reproducible an assembly step that already
happened once, undocumented, before this repository's current history began.

Running it against a fresh schema_gnrator_Bio2RDF.py run should reproduce the
already-committed canonical files (mod line ordering/whitespace), now that
schema_gnrator_Bio2RDF.py's subject-type filter explicitly excludes
`*_vocabulary:Resource` (added in the commit immediately before this one), the
same exclusion `bio2rdf_release_schema.py` already applies for the Release-2/3
schemas. Before that fix, schema_gnrator_Bio2RDF.py's own code did not exclude
Resource types, even though the committed canonical files were already
Resource-free — this script's existence (and the fix before it) closes that gap
between what the code said and what the data actually was.

INPUTS
------
Both are raw, per-run outputs of schema_gnrator_Bio2RDF.py and are not
committed to the repository (they must be regenerated by running that script
against the live Bio2RDF endpoint before this script can run):

- all_classes.csv   One column, "All Classes". One row per (graph, subject_prop)
                     combination in which a resource in that Bio2RDF dataset
                     graph is asserted to be `rdf:type` or `rdfs:subClassOf` some
                     class. The same class IRI appears multiple times (once per
                     graph/property occurrence it was found in); this file is not
                     pre-deduplicated.

- schema.csv        Three columns, "Class1", "Predicate", "Class2" — one row per
                     schema-level relationship found by the Query-2-style join:
                     a subject of class Class1, connected by Predicate to an
                     object of class Class2.

WHAT IS TAKEN FROM EACH, AND WHY Class2 IS NOT A SEPARATE SOURCE OF TYPES
--------------------------------------------------------------------------
The canonical type list is built only from all_classes.csv's "All Classes"
column (deduplicated). schema.csv's "Class2" column (the object-position type,
`otype` in schema_gnrator_Bio2RDF.py) is deliberately *not* unioned in as an
extra source of types, and this is not an oversight: schema_gnrator_Bio2RDF.py
calls fetch_subject_types(graph, property) once per (graph, property) pair,
unconditionally, over *every* subject in that graph — not only subjects that
also participate in a cross-type relationship. Every Class2 value the
relationship query can ever produce is found via that same
`?o {property} ?otype` pattern, over the same graph, for a property already in
the same fixed list ('rdf:type', 'rdfs:subClassOf') that fetch_subject_types
iterates over. So every value that could appear in Class2 is, by construction,
already present in all_classes.csv for that graph. Unioning Class2 in would add
duplicates, never new types.

The canonical predicate list is built only from schema.csv's "Predicate" column
(deduplicated). schema_gnrator_Bio2RDF.py already restricts this column to
Bio2RDF-vocabulary IRIs (the `_vocabulary:` check applied when the predicate is
written); no Resource-related filtering applies to predicates in either
extraction pipeline (bio2rdf_release_schema.py doesn't filter predicates for
Resource either), so no extra filtering is needed here.

CONSTRUCTION
------------
1. types  = sorted(set of all_classes.csv's "All Classes" column)
2. preds  = sorted(set of schema.csv's "Predicate" column)
3. schema_elements = types tagged "type", followed by preds tagged "predicate"
   (one "Schema Element,kind" row per element)

OUTPUTS AND DOWNSTREAM USAGE
------------------------------
Written under generated-usage-metadata/bio2rdf-schema/:

- types_26subgraphs.txt         -- read by bio2rdf2013_organic_coverage.py
                                    (TSE denominator; Table 3)
- predicates_26subgraphs.txt    -- read by bio2rdf2013_organic_coverage.py
                                    (TSE denominator; Table 3)
- schema_elements_26subgraphs.csv -- read by bio2rdf_recompute_conformant.py
                                    (Tables 4-5, 7, 12) and by
                                    regenerate_figures.py (Figures 5, 9, 10)

WHAT THIS SCRIPT DOES NOT COVER
----------------------------------
generated-usage-metadata/schema-Bio2RDF-17Subgraphs.csv (the 395-element subset
behind Table 3's 17-subgraph column) is NOT produced by this script, but its
derivation is now understood (2026-09-24) rather than an open question.

The manuscript describes its scope as "the 17 [of 26] subgraphs [that] have
corresponding query logs available in the Bio2RDF log2013 dataset". The exact
17-dataset allowlist survives in an orphaned notebook,
KG-Usage-analysis/Bio2RDF-federated-querying/2013KG-get_datasets_relationships_bio2rdf.ipynb
(cell 3, `allowed_vocabularies`), written for the now-removed "Pairwise Schema
Type Usage" analysis (review round 4, comment #7) but never deleted:

    sgd, taxonomy, homologene, bioportal, kegg, pharmgkb, hgnc, omim, ctd,
    drugbank, mgi, goa, wormbase, affymetrix, ncbigene, irefindex, sider

Filtering this script's own types_26subgraphs.txt/predicates_26subgraphs.txt
output to only elements whose Bio2RDF dataset-name prefix (the DATASET in
http://bio2rdf.org/DATASET_vocabulary:... or DATASET_resource:...) is in that
17-name list reproduces the committed schema-Bio2RDF-17Subgraphs.csv almost
exactly:

  - predicates: 125/125 match exactly
  - types: 271 reconstructed vs. the published 270 -- every published type is
    reproduced; the only discrepancy is one extra element,
    http://bio2rdf.org/ctd_vocabulary:Gene-Disease-Association, present in the
    live 2024 endpoint's ctd subgraph (this script's input) but absent from
    the committed 2013-scoped file. Most likely explanation: Bio2RDF's ctd
    dataset added this class sometime after 2013, so it is dataset-name
    "ctd" today but was not part of ctd's actual 2013-era schema -- a single
    dated schema-drift exception, not a flaw in the 17-name filtering rule.
  - `bioportal` is on the 17-name allowlist but contributes zero elements to
    the file: that subgraph had 2013 query-log data but no schema elements
    survived the earlier vocabulary/Resource filtering. Consistent with "17
    subgraphs have log data", not "17 subgraphs each contribute schema
    elements" -- not a contradiction.

Given this, schema-Bio2RDF-17Subgraphs.csv is left as-is (already committed,
already used, and the one discrepancy is explained rather than mysterious).
A future rebuild, should the raw all_classes.csv/schema.csv ever need
regenerating, should apply this same 17-name allowlist filter and keep the
one dated ctd exception rather than blindly trusting a pure name-prefix
filter against whatever the live endpoint returns at rebuild time.
"""
import csv

RAW_DIR = "."
OUT_DIR = "generated-usage-metadata/bio2rdf-schema"


def read_column(path, col_index):
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    return [row[col_index] for row in rows[1:] if row]


def main():
    types = sorted(set(read_column(f"{RAW_DIR}/all_classes.csv", 0)))
    preds = sorted(set(read_column(f"{RAW_DIR}/schema.csv", 1)))

    with open(f"{OUT_DIR}/types_26subgraphs.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(types))
    with open(f"{OUT_DIR}/predicates_26subgraphs.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(preds))
    with open(f"{OUT_DIR}/schema_elements_26subgraphs.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["Schema Element", "kind"])
        for t in types:
            w.writerow([t, "type"])
        for p in preds:
            w.writerow([p, "predicate"])

    print(f"types: {len(types)}  predicates: {len(preds)}  "
          f"total: {len(types) + len(preds)}")


if __name__ == "__main__":
    main()
